var engine={settings:{},defaultSettings:{useSSL:0,ip:"127.0.0.1",port:9091,path:"transmission/rpc",displayActiveTorrentCountIcon:1,showNotificationOnDownloadCompleate:1,notificationTimeout:5E3,backgroundUpdateInterval:12E4,popupUpdateInterval:1E3,login:null,password:null,hideSeedStatusItem:0,hideFnishStatusItem:0,showSpeedGraph:1,popupHeight:350,selectDownloadCategoryOnAddItemFromContextMenu:0,treeViewContextMenu:0,showDefaultFolderContextMenuItem:0,badgeColor:"0,0,0,0.40",showFreeSpace:1,guiPath:"",
requireAuthentication:1},torrentListColumnList:{},defaultTorrentListColumnList:[{column:"checkbox",display:1,order:0,width:19,lang:"selectAll"},{column:"name",display:1,order:1,width:200,lang:"OV_COL_NAME"},{column:"order",display:0,order:1,width:20,lang:"OV_COL_ORDER"},{column:"size",display:1,order:1,width:60,lang:"OV_COL_SIZE"},{column:"remaining",display:0,order:1,width:60,lang:"OV_COL_REMAINING"},{column:"done",display:1,order:1,width:70,lang:"OV_COL_DONE"},{column:"status",display:1,order:1,
width:70,lang:"OV_COL_STATUS"},{column:"seeds",display:0,order:1,width:30,lang:"OV_COL_SEEDS"},{column:"peers",display:0,order:1,width:30,lang:"OV_COL_PEERS"},{column:"seeds_peers",display:1,order:1,width:40,lang:"OV_COL_SEEDS_PEERS"},{column:"downspd",display:1,order:1,width:60,lang:"OV_COL_DOWNSPD"},{column:"upspd",display:1,order:1,width:60,lang:"OV_COL_UPSPD"},{column:"eta",display:1,order:1,width:70,lang:"OV_COL_ETA"},{column:"upped",display:0,order:1,width:60,lang:"OV_COL_UPPED"},{column:"downloaded",
display:0,order:1,width:60,lang:"OV_COL_DOWNLOADED"},{column:"shared",display:0,order:1,width:60,lang:"OV_COL_SHARED"},{column:"added",display:0,order:1,width:120,lang:"OV_COL_DATE_ADDED"},{column:"completed",display:0,order:1,width:120,lang:"OV_COL_DATE_COMPLETED"},{column:"actions",display:1,order:0,width:36,lang:"Actions"}],fileListColumnList:{},defaultFileListColumnList:[{column:"checkbox",display:1,order:0,width:19,lang:"selectAll"},{column:"name",display:1,order:1,width:300,lang:"FI_COL_NAME"},
{column:"size",display:1,order:1,width:60,lang:"FI_COL_SIZE"},{column:"downloaded",display:1,order:1,width:60,lang:"OV_COL_DOWNLOADED"},{column:"done",display:1,order:1,width:70,lang:"OV_COL_DONE"},{column:"prio",display:1,order:1,width:74,lang:"FI_COL_PRIO"}],icons:{complete:"images/notification_done.png",add:"images/notification_add.png",error:"images/notification_error.png"},capitalize:function(a){return a.substr(0,1).toUpperCase()+a.substr(1)},varCache:{webUiUrl:void 0,token:null,torrents:[],
labels:[],settings:{},lastPublicStatus:"-_-",trafficList:[{name:"download",values:[]},{name:"upload",values:[]}],startTime:parseInt(Date.now()/1E3),activeCount:0,folderList:[],rmLastScrapeResult:/"lastScrapeResult":"[^"]+","/gm},api:{getTorrentListRequest:{method:"torrent-get",arguments:{fields:"id name totalSize percentDone downloadedEver uploadedEver rateUpload rateDownload eta peersSendingToUs peersGettingFromUs queuePosition addedDate doneDate downloadDir recheckProgress status error errorString trackerStats magnetLink".split(" "),
ids:void 0}},getFileListRequest:{method:"torrent-get",arguments:{fields:["id","files","fileStats"],ids:void 0}},trUtColumnList:"id statusCode name totalSize progress downloadedEver uploadedEver shared rateUpload rateDownload eta _label peersGettingFromUs peers peersSendingToUs seeds n_unk queuePosition n_uploaded t_unk1 t_unk2 statusText n_sid addedDate doneDate t_unk3 downloadDir t_unk4 n_unk5 magnetLink".split(" "),flUtColumnList:"name length bytesCompleted priority origName folderName".split(" ")},
param:function(a){if("string"===typeof a)return a;var b=[],d;for(d in a)if(a.hasOwnProperty(d)){if(void 0===a[d]||null===a[d])a[d]="";b.push(encodeURIComponent(d)+"="+encodeURIComponent(a[d]))}return b.join("&")},publicStatus:function(a){engine.varCache.lastPublicStatus!==a&&(engine.varCache.lastPublicStatus=a,mono.sendMessage({setStatus:a}))},parseXhrHeader:function(a){a=a.split(/\r?\n/);var b={};a.forEach(function(a){var c=a.indexOf(":");if(-1!==c){var d=a.substr(0,c).trim().toLowerCase();a=a.substr(c+
1).trim();b[d]=a}});return b},request:function(a,b){var d={},c=function(a,d){c=null;h.timeoutTimer&&clearTimeout(h.timeoutTimer);var e=null;a&&(e=String(a.message||a)||"ERROR");a={statusCode:0,statusText:"",headers:{},body:""};if(l){a.statusCode=l.status;a.statusText=l.statusText;var g=null,f=l.getAllResponseHeaders();"string"===typeof f&&(g=engine.parseXhrHeader(f));a.headers=g||{};a.body=d||""}b&&b(e,a,d)};"object"!==typeof a&&(a={url:a});var f=a.url,e=a.method||a.type||"GET";e=e.toUpperCase();
var g=a.data,k=!1;"string"!==typeof g&&((k="[object FormData]"===String(g))||(g=engine.param(g)));g&&"GET"===e&&(f+=(/\?/.test(f)?"&":"?")+g,g=void 0);!1===a.cache&&-1!==["GET","HEAD"].indexOf(e)&&(f+=(/\?/.test(f)?"&":"?")+"_="+Date.now());a.headers=a.headers||{};g&&!k&&(a.headers["Content-Type"]=a.contentType||a.headers["Content-Type"]||"application/x-www-form-urlencoded; charset=UTF-8");var h={};h.url=f;h.method=e;g&&(h.data=g);a.json&&(h.json=!0);a.xml&&(h.xml=!0);a.timeout&&(h.timeout=a.timeout);
a.mimeType&&(h.mimeType=a.mimeType);a.withCredentials&&(h.withCredentials=!0);Object.keys(a.headers).length&&(h.headers=a.headers);0<h.timeout&&(h.timeoutTimer=setTimeout(function(){c&&c(Error("ETIMEDOUT"));l.abort()},h.timeout));var m={0:200,1223:204},l=new XMLHttpRequest;l.open(h.method,h.url,!0);h.mimeType&&l.overrideMimeType(h.mimeType);h.withCredentials&&(l.withCredentials=!0);for(var n in h.headers)l.setRequestHeader(n,h.headers[n]);l.onload=function(){var a=m[l.status]||l.status;try{if(200<=
a&&300>a||304===a){var b=l.responseText;if(h.json)b=JSON.parse(b);else if(h.xml)b=(new DOMParser).parseFromString(b,"text/xml");else if("string"!==typeof b)throw console.error("Response is not string!",b),Error("Response is not string!");return c&&c(null,b)}throw Error(l.status+" "+l.statusText);}catch(r){return c&&c(r)}};var t=l.onerror=function(){c&&c(Error(l.status+" "+l.statusText))};a=null;void 0!==l.onabort?l.onabort=t:a=function(){4===l.readyState&&c&&setTimeout(function(){return t()})};a&&
(l.onreadystatechange=a);try{l.send(h.data||null)}catch(q){setTimeout(function(){c&&c(q)})}d.abort=function(){c=null;l.abort()};return d},timer:{timer:null,state:0,start:function(){this.state=1;this.timer&&clearInterval(this.timer);this.timer=null;1E3>=engine.settings.backgroundUpdateInterval||(this.timer=setInterval(function(){engine.updateTrackerList()},engine.settings.backgroundUpdateInterval))},stop:function(){this.timer&&clearInterval(this.timer);this.timer=null;this.state=0}},tr2utStatus:function(a){if(0===
a){a=128;var b="Stopped"}else 1===a?(a=233,b="Queued to check files"):2===a?(a=130,b="Checking"):3===a?(a=200,b="Queued to download"):4===a?(a=201,b="Downloading"):5===a?(a=200,b="Queued to seed"):6===a?(a=201,b="Seeding"):(a=152,b="Unknown");return[a,b]},tr2utTrList:function(a,b){a.ut={};if(!b.arguments)return a;var d="recently-active"===b.arguments.ids?"torrentp":"torrents",c=a.arguments;if(void 0!==c.torrents){var f=c.torrents[0];if(f&&void 0!==f.files){b=a.ut.files=[];b[0]="trId"+f.id;c=b[1]=
[];for(var e,g=0;d=f.files[g];g++){if(void 0===e&&(e=d.name.indexOf("/"),-1===e)){e=null;break}if(d.name.indexOf("/")!==e){e=null;break}}for(g=0;d=f.files[g];g++){d.priority=f.fileStats[g].wanted?f.fileStats[g].priority+2:0;d.origName=d.name;d.folderName="";null!==e&&(d.folderName=d.name.substr(0,e+1),d.name=d.name.substr(e+1));var k=[];b=0;for(var h;h=engine.api.flUtColumnList[b];b++)k.push(d[h]);c.push(k)}return a}a.ut[d]=[];for(b=0;e=c.torrents[b];b++){e.id="trId"+e.id;g=[];0<e.error?(g[0]=144,
g[1]=engine.language.OV_FL_ERROR+": "+(e.errorString||"Unknown error")):g=engine.tr2utStatus(e.status);e.statusCode=g[0];e.statusText=g[1];e.percentDone=e.percentDone||0;e.progress=parseInt(1E3*(e.recheckProgress||e.percentDone));e.shared=0<e.downloadedEver?Math.round(e.uploadedEver/e.downloadedEver*1E3):0;0>e.eta&&(e.eta=0);f=h=0;if(void 0!==e.trackerStats)for(g=0;k=e.trackerStats[g];g++)0<k.leecherCount&&(h+=k.leecherCount),0<k.seederCount&&(f+=k.seederCount);e.peers=h;e.seeds=f;e.queuePosition=
e.queuePosition||0;e.downloadDir=e.downloadDir||0;f=[];for(g=0;h=engine.api.trUtColumnList[g];g++)void 0!==e[h]?f.push(e[h]):"n"===h[0]?f.push(0):f.push("");a.ut[d].push(f)}}if("torrents"===d&&void 0!==a.ut.torrents){c=[];for(b=0;d=engine.varCache.torrents[b];b++){e=!1;for(g=0;h=a.ut.torrents[g];g++)if(h[0]===d[0]){e=!0;break}e||c.push(d[0])}0<c.length&&(a.ut.torrentm=c)}else if(void 0!==c.removed)for(a.ut.torrentm=[],b=0,g=c.removed.length;b<g;b++)a.ut.torrentm.push("trId"+c.removed[b]);a.ut.torrentc=
Date.now();return a},sendAction:function(a,b,d,c){var f={};engine.settings.requireAuthentication&&null!==engine.settings.login&&null!==engine.settings.password&&(f.Authorization="Basic "+btoa(engine.settings.login+":"+engine.settings.password));null!==engine.varCache.token&&(f["X-Transmission-Session-Id"]=engine.varCache.token);engine.request({type:"POST",url:engine.varCache.webUiUrl,headers:f,data:JSON.stringify(a)},function(e,g,f){if(e){c=c||0;c++;409===g.statusCode&&(engine.varCache.token=g.headers["x-transmission-session-id"]);
if(2>c)return engine.sendAction.call(engine,a,b,d,c);engine.publicStatus("Can't send action! "+e);return d&&d(e)}try{f=f.replace(engine.varCache.rmLastScrapeResult,'"lastScrapeResult":"","'),f=JSON.parse(f)}catch(h){return engine.publicStatus("Data parse error!")}engine.publicStatus("");engine.tr2utTrList(f,a);b&&b(f);engine.readResponse(f,a)})},readResponse:function(a,b){var d=a.ut;if(void 0!==d.torrentm)for(var c=engine.varCache.torrents,f=0,e;e=d.torrentm[f];f++)for(var g=0,k;k=c[g];g++)if(k[0]===
e){c.splice(g,1);break}c=d.torrents||d.torrentp;void 0!==c&&engine.utils(engine.varCache.torrents,c);if(void 0!==d.torrents)engine.varCache.torrents=d.torrents;else if(void 0!==d.torrentp){c=engine.varCache.torrents;e=[];f=0;for(var h;h=d.torrentp[f];f++){var m=!1;for(g=0;k=c[g];g++)if(k[0]===h[0]){c[g]=h;m=!0;break}!1===m&&(e.push(h),c.push(h))}}"session-get"===b.method&&(engine.varCache.settings=a.arguments);engine.settings.displayActiveTorrentCountIcon&&engine.displayActiveItemsCountIcon(engine.varCache.torrents)},
updateTrackerList:function(){engine.sendAction(engine.api.getTorrentListRequest,function(a){},function(){engine.timer.stop()})},loadSettings:function(a){var b=engine.defaultSettings,d=[],c;for(c in b)d.push(c);var f=["fileListColumnList","torrentListColumnList"];f.forEach(function(a){d.push(a)});d.push("language");d.push("folderList");d.push("ut_port");d.push("ut_ip");d.push("ut_path");d.push("ssl");mono.storage.local.get(d,function(c){var d={};c.hasOwnProperty("port")||!c.ut_port||isNaN(parseInt(c.ut_port))||
(c.port=parseInt(c.ut_port));!c.hasOwnProperty("ip")&&c.ut_ip&&(c.ip=c.ut_ip);!c.hasOwnProperty("path")&&c.path&&(c.path=c.ut_path);c.hasOwnProperty("useSSL")||1!==c.ssl||(c.useSSL=c.ssl);for(var e in b)d[e]=c.hasOwnProperty(e)?c[e]:b[e];d.lang=c.language;engine.varCache.folderList=c.folderList||engine.varCache.folderList;engine.settings=d;f.forEach(function(a){var b="default"+engine.capitalize(a);engine[a]=c.hasOwnProperty(a)?c[a]:engine[b];if(engine[b].length!==engine[a].length)for(var d=0,e;e=
engine[b][d];d++){for(var f=!1,g=0,h;h=engine[a][g];g++)if(h.column===e.column){f=!0;break}f||("checkbox"===e.column?engine[a].unshift(e):engine[a].push(e))}});engine.varCache.webUiUrl=(d.useSSL?"https://":"http://")+d.ip+":"+d.port+"/"+d.path;return a()})},setLanguage:function(a){var b=engine.language,d;for(d in a)b[d]=a[d]},getNavLanguage:function(){var a="",b=navigator.language;/^\w{2}-|^\w{2}$/.test(b)&&(a=b);return a},loadLanguage:function(a){var b=engine.settings.lang;"string"===typeof b&&(b=
b.substr(0,2));(function e(a,b){/^pt/.test(a)?a="pt_BR":/^zh/.test(a)&&(a="zh_CN");mono.getLanguage(a,function(c,f){c?"en"!==a?e("en",b):b():(engine.setLanguage(f),b())})})(b||mono.getLoadedLocale(),a)},getLanguage:function(a){engine.language={};engine.loadLanguage(a)},trafficCounter:function(a){for(var b=0,d=0,c=0,f;f=a[c];c++)b+=f[9],d+=f[8];a=engine.varCache.trafficList[0].values;c=engine.varCache.trafficList[1].values;f=parseInt(Date.now()/1E3)-engine.varCache.startTime;a.push({time:f,pos:b});
c.push({time:f,pos:d});90<a.length&&(a.shift(),c.shift())},showNotification:function(a,b,d,c){c=c||{};c.notificationTimeout=engine.settings.notificationTimeout;mono.showNotification(a,b,d,c)},onCompleteNotification:function(a,b){if(0!==a.length)for(var d=0,c;c=b[d];d++)if(1E3===c[4])for(var f=0,e;e=a[f];f++)e[0]!==c[0]||1E3===e[4]||e[24]||engine.showNotification(engine.icons.complete,c[2],void 0!==c[21]?engine.language.OV_COL_STATUS+": "+c[21]:"")},setBadgeText:function(a){engine.setBadgeText.lastText=
a;mono.setBadgeText(a);engine.settings.badgeColor&&mono.setBadgeBackgroundColor(engine.settings.badgeColor)},displayActiveItemsCountIcon:function(a){for(var b=0,d=0,c;c=a[d];d++)1E3===c[4]||void 0!==c[24]&&0!==c[24]||b++;engine.varCache.activeCount!==b&&(engine.varCache.activeCount=b,engine.setBadgeText(b?String(b):""))},utils:function(a,b){engine.settings.showSpeedGraph&&engine.trafficCounter(b);engine.settings.showNotificationOnDownloadCompleate&&engine.onCompleteNotification(a.slice(0),b)},downloadFile:function(a,
b,d){var c=new XMLHttpRequest;try{c.open("GET",a,!0)}catch(f){engine.showNotification(engine.icons.error,c.status,engine.language.unexpectedError);return}c.responseType="blob";d&&c.setRequestHeader("Referer",d);c.onprogress=function(a){if(10485760<a.total||10485760<a.loaded)c.abort(),engine.showNotification(engine.icons.error,engine.language.OV_FL_ERROR,engine.language.fileSizeError)};c.onload=function(){return b(c.response)};c.onerror=function(){0===c.status?engine.showNotification(engine.icons.error,
c.status,engine.language.unexpectedError):engine.showNotification(engine.icons.error,c.status,c.statusText)};c.send()},sendFile:function(a,b,d,c){var f;if((f="string"===typeof a)&&"magnet:"!==a.substr(0,7).toLowerCase())engine.downloadFile(a,function(e){"blob:"===a.substr(0,5).toLowerCase()&&URL.revokeObjectURL(a);engine.sendFile(e,b,d,c)},c);else{var e={method:"torrent-add",arguments:{}};f?e.arguments.filename=a:e.arguments.metainfo=a;b&&(e.arguments["download-dir"]=b.path);var g=function(){engine.sendAction(e,
function(a){a.result&&"success"!==a.result?engine.showNotification(engine.icons.error,engine.language.OV_FL_ERROR,a.result):(a.arguments["torrent-added"]?(a=a.arguments["torrent-added"].name,engine.settings.selectDownloadCategoryOnAddItemFromContextMenu&&mono.storage.local.set({selectedLabel:{label:"DL",custom:1}}),engine.showNotification(engine.icons.add,a,engine.language.torrentAdded)):a.arguments["torrent-duplicate"]&&(a=a.arguments["torrent-duplicate"].name,engine.showNotification(engine.icons.error,
a,engine.language.torrentFileIsExists)),engine.updateTrackerList())})};if(void 0!==e.arguments.filename)return g();var k=new FileReader;k.readAsDataURL(e.arguments.metainfo);k.onloadend=function(){var a=k.result.indexOf(",");e.arguments.metainfo=k.result.substr(a+1);g()}}},onCtxMenuCall:function(a){var b=a.linkUrl,d=a.menuItemId,c=!1,f=engine.createFolderCtxMenu.contextMenu,e=f[0]?f[0]:["0","",""];if("newFolder"===d){var g=prompt(engine.language.enterNewDirPath,e[1]);if(!g)return;e=e[0];d=-1;for(var k=
0,h;h=f[k];k++)if(h[1]===g&&h[0]===e){d=k;break}-1===d&&(d=f.length,f.push([e,g,""]),engine.varCache.folderList.push([e,g,""]),c=!0)}if("main"===d||"default"===d)return engine.sendFile(b,void 0,void 0,a.referer);var m,l;h=f[d];"string"===typeof h?l=h:m={download_dir:h[0],path:h[1]};c&&mono.storage.local.set({folderList:engine.varCache.folderList},function(){engine.createFolderCtxMenu()});engine.sendFile(b,m,l,a.referer)},listToTreeList:function(a){for(var b=[],d={},c,f=0,e=0,g;g=a[e];e++){var k=g[1];
void 0===c?c=-1===k.indexOf("/")?-1===k.indexOf("\\")?void 0:"\\":"/":g[1]="\\"===c?k.replace(/\//g,"\\"):k.replace(/\\/g,"/")}void 0===c&&(c="");for(e=0;g=a[e];e++){var h=g[0];if(k=g[1]){g=c+c;var m=[];if(0===k.search(/[a-zA-Z]{1}:(\/\/|\\\\)/)){var l=k.split(":"+g);2===l.length&&(l[0]+=":"+g,m.push(l[0]),k=l[1])}k=0!==c.length?k.split(c):[k];m=m.concat(k);""===m[0]&&(m.shift(),m[0]=c+m[0]);""===m.slice(-1)[0]&&m.splice(-1);l=k=void 0;for(var n=0,t=m.length;n<t;n++){var q=void 0!==k?k:d,p=m[n];l=
void 0===l?p:1===n&&l.slice(-3)===":"+g?l+p:l+(c+p);k=q[p];void 0===k&&(q===d&&f++,k=q[p]={arrayIndex:b.length,currentPath:p},b.push([h,l]))}k&&(k.end=!0)}}var r=[],u=function(a,b){var d=[];for(f in b){var e=b[f];void 0!==e.currentPath&&d.push(e)}var f=d.length;if(1===f&&void 0===b.end)f=b.currentPath,b.currentPath.slice(-1)!==c&&(f+=c),d[0].currentPath=f+d[0].currentPath,u(a,d[0]);else{var g=(f=0!==f)?"p"+String(b.arrayIndex):String(b.arrayIndex);b.currentPath&&(r.push({id:g,parentId:a,title:b.currentPath}),
f&&r.push({id:g.substr(1),parentId:g,title:engine.language.currentDirectory}));d.forEach(function(a){u(g,a)})}};for(g in d)u("main",d[g]);return{tree:r,list:b}},createFolderCtxMenu:function(){mono.contextMenusRemoveAll(function(){var a=engine.createFolderCtxMenu.contextMenu=[],b=engine.varCache.folderList;mono.contextMenusCreate({id:"main",title:engine.language.addInTorrentClient,contexts:["link"],onclick:engine.onCtxMenuCall},function(){Array.prototype.push.apply(a,b);if(0<b.length)if(engine.settings.treeViewContextMenu){for(var d=
engine.listToTreeList(b.slice(0)),c=0,f;f=d.tree[c];c++)mono.contextMenusCreate({id:f.id,parentId:f.parentId,title:f.title,contexts:["link"],onclick:engine.onCtxMenuCall});a.splice(0);Array.prototype.push.apply(a,d.list)}else for(c=0;f=b[c];c++)mono.contextMenusCreate({id:String(c),parentId:"main",title:f[2]||f[1],contexts:["link"],onclick:engine.onCtxMenuCall});engine.settings.showDefaultFolderContextMenuItem&&mono.contextMenusCreate({id:"default",parentId:"main",title:engine.language.defaultPath,
contexts:["link"],onclick:engine.onCtxMenuCall});(0<b.length||engine.settings.showDefaultFolderContextMenuItem)&&mono.contextMenusCreate({id:"newFolder",parentId:"main",title:engine.language.add+"...",contexts:["link"],onclick:engine.onCtxMenuCall})})})},run:function(){engine.loadSettings(function(){engine.getLanguage(function(){engine.varCache.isReady=1;for(var a=engine.varCache.msgStack,b,d;d=a.shift();)if(b=engine.onMessage.apply(engine,d),!0!==b)d[2](null);engine.updateTrackerList();engine.timer.start();
engine.createFolderCtxMenu()})})},onMessage:function(a,b,d){if(1!==engine.varCache.isReady)return engine.varCache.msgStack.push(arguments),!0;var c=engine.actionList[a.action];return c&&c(a,d)},storageCache:{},hookList:{getTorrentList:function(a,b){var d=engine.api.getTorrentListRequest;a.cid&&(d=utils.cloneObj(d),d.arguments.ids="recently-active");engine.sendAction(d,function(a){if("success"!==a.result)return b(null);b(a.ut)})}},actionList:{getLanguage:function(a,b){b(engine.language)},getSettings:function(a,
b){b(engine.settings)},getDefaultSettings:function(a,b){b(engine.defaultSettings)},getTrColumnArray:function(a,b){b(engine.torrentListColumnList)},getFlColumnArray:function(a,b){b(engine.fileListColumnList)},getRemoteTorrentList:function(a,b){b(engine.varCache.torrents)},getRemoteSettings:function(a,b){b(engine.varCache.settings)},getPublicStatus:function(a,b){b(engine.varCache.lastPublicStatus)},api:function(a,b){var d=engine.hookList[a.data.action];void 0!==d?d(a.data,b):engine.sendAction(a.data,
b);return!0},sessionSet:function(a,b){engine.sendAction(a.data,function(d){if("success"===d.result)for(var c in a.data.arguments)engine.varCache.settings[c]=a.data.arguments[c];b(d)});return!0},setTrColumnArray:function(a,b){engine.torrentListColumnList=a.data;mono.storage.local.set({torrentListColumnList:a.data},b);return!0},setFlColumnArray:function(a,b){engine.fileListColumnList=a.data;mono.storage.local.set({fileListColumnList:a.data},b);return!0},onSendFile:function(a,b){if(a.base64){b=a.base64;
var d=a.type;delete a.base64;delete a.type;a.url=utils.base64ToUrl(b,d)}engine.sendFile(a.url,a.folder,a.label)},getTraffic:function(a,b){b({trafficList:engine.varCache.trafficList,startTime:engine.varCache.startTime})},checkSettings:function(a,b){engine.loadSettings(function(){engine.getLanguage(function(){engine.sendAction(engine.api.getTorrentListRequest,function(a){return"success"!==a.result?b({error:a.result}):b({})},function(a){return b({error:a})})})});return!0},reloadSettings:function(a,b){engine.loadSettings(function(){engine.getLanguage(function(){engine.createFolderCtxMenu();
!engine.settings.displayActiveTorrentCountIcon&&0<engine.varCache.activeCount&&(engine.varCache.activeCount=0,engine.setBadgeText(""));b()})});return!0},managerIsOpen:function(a,b){1!==engine.timer.state&&engine.timer.start()},getFileList:function(a,b){engine.api.getFileListRequest.arguments.ids=[parseInt(a.hash.substr(4))];engine.sendAction(engine.api.getFileListRequest,function(a){"success"===a.result&&b(a.ut)});return!0},changeBadgeColor:function(a){engine.settings.badgeColor=a.color;engine.setBadgeText(engine.setBadgeText.lastText||
"0")},copy:function(a){mono.addInClipboard(a.text)}},init:function(){engine.setBadgeText("");engine.varCache.msgStack=[];mono.onMessage.addListener(engine.onMessage);engine.run()}};mono.onReady(function(){engine.init()});
