var options=function(){var k=null,l=void 0,d={},n={},r=function(){for(var c in options.defaultSettings){var a=options.defaultSettings[c],b=document.querySelector('input[data-option="'+c+'"]');if(null===b)console.log("El not found!",c);else if(-1!==["text","number","password"].indexOf(b.type)){if(b.value=options.settings[c]!==a?options.settings[c]:"",a||""===a||0===a)b.placeholder=a}else"checkbox"===b.type?b.checked=!!options.settings[c]:"radio"===b.type&&(a=document.querySelector('input[data-option="'+
c+'"][value="'+options.settings[c]+'"]'),null!==a&&(b=a),b.checked=!0)}},p=function(){var c=location.hash.substr(1)||"client";c=document.querySelector('a[data-page="'+c+'"]');null===c&&(c=document.querySelector('a[data-page="client"]'));c.dispatchEvent(new CustomEvent("click",{bubbles:!0}))},m=function(c){var a=c.target;if("INPUT"===a.tagName&&(c=a.dataset.option)){if("checkbox"===a.type)var b=a.checked?1:0;else if("radio"===a.type)b=parseInt(a.value);else if("number"===a.type){b=parseInt(a.value);
isNaN(b)&&(b=parseInt(a.placeholder));var d=parseInt(a.min);!isNaN(d)&&b<d&&(b=d,a.value=b);if(isNaN(b))return}else-1!==["text","password"].indexOf(a.type)&&(b=a.value,a=a.placeholder,!b&&a&&(b=a));a={};a[c]=b;var f=this.cb;mono.storage.local.set(a,function(){mono.sendMessage({action:"reloadSettings"},f)})}},q=function(c){mono.storage.local.get(null,function(a){c&&c(JSON.stringify(a))})},t=function(c){mono.storage.local.clear();var a={},b;for(b in c){var d=c[b];!1!==c.hasOwnProperty(b)&&null!==d&&
(a[b]=d)}mono.storage.local.set(a,function(){mono.sendMessage({action:"reloadSettings"},function(){window.location.reload()})})},u=function(){d.backupUpdateBtn.on("click",function(){q(function(c){d.backupInp.val(c)})});d.restoreBtn.on("click",function(){try{var c=JSON.parse(d.restoreInp.val())}catch(a){return alert(options.language.OV_FL_ERROR+"\n"+a)}t(c)});d.clearCloudStorageBtn.on("click",function(){mono.storage.sync.clear();d.getFromCloudBtn.prop("disabled",!0)});d.saveInCloudBtn.on("click",function(){var c=
this;c.disabled=!0;setTimeout(function(){c.disabled=!1},750);q(function(a){mono.storage.sync.set({backup:a},function(){d.getFromCloudBtn.prop("disabled",!1)})})});d.getFromCloudBtn.on("click",function(){mono.storage.sync.get("backup",function(c){d.restoreInp.val(c.backup)})})},v=function(c){c=(c||document).querySelectorAll("[data-lang]");for(var a=0,b;b=c[a];a++)for(var d=b.dataset.lang.split("|"),f=0,g;g=d[f];f++){g=g.split(",");var h=options.language[g.shift()];void 0===h?console.log("Language string is not found!",
b.dataset.lang):0!==g.length?g.forEach(function(a){if("text"===a)return b.textContent=h,1;b.setAttribute(a,h)}):"DIV"===b.tagName?b.title=h:-1!=="A LEGEND SPAN LI TH P OPTION BUTTON H2 H3".split(" ").indexOf(b.tagName)?b.textContent=h:"INPUT"===b.tagName?b.value=h:console.log("Tag name not found!",b.tagName)}},w=function(c){for(var a=0,b;b=c[a];a++)d.folderList.appendChild(utils.create("option",{text:(b[2]?"["+b[2]+"] ":"")+b[1],data:{dir:b[0],subPath:b[1],label:b[2]||""}}))},x=window.folderSaveList=
function(){for(var c=[],a=d.folderList.childNodes,b=0,e;e=a[b];b++)c.push([e.dataset.dir,e.dataset.subPath,e.dataset.label]);mono.storage.local.set({folderList:c},function(){mono.sendMessage({action:"reloadSettings"})})},y=function(c){for(var a=[],b=d[c+"List"].childNodes,e=0,f;f=b[e];e++)f.selected&&a.push(f);for(e=0;f=a[e];e++)f.parentNode.removeChild(f);window[c+"SaveList"]()},z=function(c){var a=d[c+"List"],b=a.selectedIndex;-1!==b&&(b=a.childNodes[b],b.previousElementSibling&&(a.insertBefore(b,
b.previousElementSibling),window[c+"SaveList"]()))},A=function(c){var a=d[c+"List"],b=a.selectedIndex;if(-1!==b){b=a.childNodes[b];var e=b.nextElementSibling;e&&(e.nextElementSibling?a.insertBefore(b,e.nextElementSibling):a.appendChild(b),window[c+"SaveList"]())}},B=function(){var d=!1,a=document.querySelector('input[data-option="badgeColor"]'),b=$(a.parentNode.querySelector(".selectColor")),e=options.settings.badgeColor;b.data("color","rgba("+e+")");b.css("backgroundColor","rgba("+e+")");a.addEventListener("keyup",
function(){b.colorpicker("setValue","rgba("+a.value+")")});a.addEventListener("focus",function(){d=!0});a.addEventListener("blur",function(){d=!1});b.colorpicker();b.on("changeColor.colorpicker",function(c){c=c.color.toRGB();e=c=c.r+","+c.g+","+c.b+","+c.a;b.css("backgroundColor","rgba("+c+")");mono.sendMessage({action:"changeBadgeColor",color:c});d||(a.value=e)});b.on("hidePicker.colorpicker",function(){a.dispatchEvent(new CustomEvent("keyup"))})};return{start:function(){mono.storage.local.get(["folderList"],
function(c){utils.joinMessages([{action:"getLanguage"},{action:"getSettings"},{action:"getTrColumnArray"},{action:"getFlColumnArray"},{action:"getDefaultSettings"}]).then(function(a){options.settings=a.getSettings;options.defaultSettings=a.getDefaultSettings;options.language=a.getLanguage;var b=document.getElementById("language");a="ru en fr zh-CN es pt-BR".split(" ").indexOf(options.language.lang);-1===a&&(a=1);b.selectedIndex=a;b.addEventListener("change",function(){mono.storage.local.set({language:b.childNodes[b.selectedIndex].value},
function(){mono.sendMessage({action:"reloadSettings"},function(){location.reload()})})});v();document.body.classList.remove("loading");d.folderList=document.getElementById("folderList");w(c.folderList||[]);d.subPath=document.getElementById("subPath");d.pathLabel=document.getElementById("pathLabel");d.addSubPath=document.getElementById("addSubPath");d.addSubPath.addEventListener("click",function(){var a=d.subPath.value;if(a){var b=d.pathLabel.value;d.folderList.appendChild(utils.create("option",{text:(b?
"["+b+"] ":"")+a,data:{dir:"0",subPath:a,label:b}}));d.subPath.value="";d.pathLabel.value="";x()}});d.subPath.addEventListener("keydown",function(a){13===a.keyCode&&d.addSubPath.dispatchEvent(new CustomEvent("click"))});d.pathLabel.addEventListener("keydown",function(a){13===a.keyCode&&d.addSubPath.dispatchEvent(new CustomEvent("click"))});d.folderDeleteSelected=document.getElementById("folderDeleteSelected");d.folderDeleteSelected.addEventListener("click",y.bind(null,"folder"));d.folderUp=document.getElementById("folderUp");
d.folderUp.addEventListener("click",z.bind(null,"folder"));d.folderDown=document.getElementById("folderDown");d.folderDown.addEventListener("click",A.bind(null,"folder"));d.backupUpdateBtn=$("#backupUpdate");d.restoreBtn=$("#restoreBtn");d.saveInCloudBtn=$("#saveInCloud");d.getFromCloudBtn=$("#getFromCloudBtn");d.clearCloudStorageBtn=$("#clearCloudStorage");d.backupInp=$("#backupInp");d.restoreInp=$("#restoreInp");r();B();u();d.menu=document.querySelector(".menu");d.menu.addEventListener("click",
function(a){a=a.target;"A"!==a.tagName||a.classList.contains("active")||(l&&l.classList.remove("active"),l=a,l.classList.add("active"),k&&k.classList.remove("active"),a=a.dataset.page,k=document.querySelector(".page."+a),k.classList.add("active"),"backup"===a&&d.backupUpdateBtn.trigger("click"),"restore"===a&&mono.storage.sync.get("backup",function(a){void 0===a.backup&&d.getFromCloudBtn.prop("disabled",!0)}))});window.addEventListener("hashchange",p);p();d.clientCheckBtn=document.getElementById("clientCheckBtn");
d.clientCheckBtn.addEventListener("click",function(a){var b=document.getElementById("clientStatus");b.textContent="";b.appendChild(utils.create("img",{src:"images/loading.gif"}));mono.sendMessage({action:"checkSettings"},function(a){b.textContent="";if(a.error)a=utils.create("span",{text:a.error,style:{color:"red"}});else if(a=utils.create("span",{text:options.language.DLG_BTN_OK,style:{color:"green"}}),!mono.isTab())return window.location="manager.html";b.appendChild(a);clearTimeout(n.statusTimer);
n.statusTimer=setTimeout(function(){b.textContent=""},2500)})});var e=document.querySelectorAll('input[data-option="login"], input[data-option="password"], input[data-option="ip"], input[data-option="port"]');a=0;for(var f;f=e[a];a++)f.addEventListener("keydown",function(a){13===a.keyCode&&m.call({cb:function(){d.clientCheckBtn.dispatchEvent(new CustomEvent("click"))}},{target:this})});e=document.querySelectorAll("input[type=text], input[type=password], input[type=number]");for(a=0;f=e[a];a++)f.addEventListener("keyup",
utils.debounce(m,500));document.body.addEventListener("click",m)})})}}}();mono.onReady(function(){options.start()});
